config/routes.rb
Raor::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :events do
    resources :checkins do
      get 'rafflr'
    end
    get 'carousel'
    get 'rafflr'
  end
  resources :admin_users, :controller => "users"
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  has_many :checkins
  belongs_to :creator, :class_name => "User"
  has_many :users, :through => :checkins

  attr_accessor :current_user
  attr_accessible :description, :end_date, :end_time, :name, :start_date, :start_time, :as => :default
  attr_accessible :created_at, :creator_id, :description, :end_date, :end_time, :id, :name, :start_date, :start_time, :updated_at, :as => :admin

  validates :name, :format => {:with => /\A[\x20-\x7E]+\z/}, :length => {:within => 2..254}, :presence => true
  validates :description, :format => {:with => /\A[\x20-\x7E]*\z/}, :length => {:within => 0..254}
  validates :start_datetime, :date => {:before => :end_datetime}
  validates :start_datetime, :date => {:after => Proc.new {5.minutes.ago}}, :on => :create
  validates :end_datetime, :date => {:after => :start_datetime}

  def self.active
    where("\"events\".\"end_datetime\" > ? AND \"events\".\"start_datetime\" <= ?", Time.zone.now, Time.zone.now)
  end

  def self.current
    where("\"events\".\"end_datetime\" >= ?", Time.zone.now).order("\"events\".\"end_datetime\" ASC")
  end

  def active?
    now = Time.zone.now
    self.end_datetime > now && self.start_datetime <= now
  end

  def current_user
    @user
  end

  def current_user=(user)
    self.creator_id = user.id unless self.creator_id
    @user = user
  end

  def is_checked_in user=nil
    user ||= current_user
    !users.find_by_id(user).nil?
  end

  def is_in_rafflr user=nil
    user ||= current_user
    checkins.find_by_user_id(user).try(:rafflr)
  end

  def start_date
    self.start_datetime.to_date.to_s if self.start_datetime
  end

  def start_date=(value)
    self.start_datetime = Time.zone.parse("#{value} #{self.start_datetime.strftime('%H:%M:00') if self.start_datetime}")
  end

  def start_time
    self.start_datetime.strftime('%I:%M %p') if self.start_datetime
  end

  def start_time=(value)
    self.start_datetime = Time.zone.parse("#{self.start_datetime ? self.start_datetime.to_date.to_s : Time.zone.now.to_date.to_s} #{value} #{Time.zone.now.zone}")
  end

  def end_date
    self.end_datetime.to_date.to_s if self.end_datetime
  end

  def end_date=(value)
    self.end_datetime = Time.zone.parse("#{value} #{self.end_datetime.strftime('%H:%M:00') if self.end_datetime}")
  end

  def end_time
    self.end_datetime.strftime('%I:%M %p') if self.end_datetime
  end

  def end_time=(value)
    self.end_datetime = Time.zone.parse("#{self.end_datetime ? self.end_datetime.to_date.to_s : Time.zone.now.to_date.to_s} #{value} #{Time.zone.now.zone}")
  end
end

app/controllers/events_controller.rb
require 'active_support/inflector'

class EventsController < ApplicationController
  include ActiveSupport::Inflector
  load_resource :event
  authorize_resource :event, :except => :index

  respond_to :html, :json

  def index
    # Must manually authorize due to setting current_user on events
    if can?(:read, Event) && can?(:read, User)
      @events = @events.page(params[:page])
      @events.each{|event| event.current_user = current_user}

      respond_with(@events) do |format|
        format.html do
          render
        end
      end
    end
  end

  def show
    @event.current_user = current_user
    @checkins = if params[:work]
      @event.checkins.employment
    elsif params[:hire]
      @event.checkins.employ
    else
      @event.checkins
    end

    respond_with(@event)
  end

  def new
    respond_with(@event)
  end

  def create
    params[:event]["creator_id"] = current_user.id.to_s
    @event.assign_attributes(params[:event], :as => as_what?)

    respond_with(@event) do |format|
      format.html do
        if can?(:manage, @event) && @event.save
          flash[:notice] = "Successfully created event #{@event.name}"
          redirect_to event_path(@event)
        else
          flash[:notice] = "SD: #{@event.start_datetime} ED: #{@event.end_datetime}"
          flash[:alert] = @event.errors.map{|attr, msg| "#{humanize(attr)} #{msg}"}.join("<br />")
          render :new
        end
      end
    end
  end

  def edit
    respond_with(@event)
  end

  def update
    respond_with(@event) do |format|
      format.html do
        if can?(:manage, @event) && @event.update_attributes(params[:event])
          flash[:notice] = "Successfully updated event #{@event.name}"
          redirect_to event_path(@event)
        else
          flash[:notice] = "SD: #{@event.start_datetime} ED: #{@event.end_datetime}"
          flash[:alert] = "Failed to update event #{@event.name}"
          redirect_to edit_event_path(@event)
        end
      end
    end
  end

  def destroy
    respond_with(@event) do |format|
      format.html do
        if can?(:manage, @event) && @event.destroy
          flash[:notice] = "Successfully destroyed event"
          redirect_to events_path
        else
          flash[:alert] = "Failed to destroy event #{@event.name}"
          render :show
        end
      end
    end
  end

  def carousel
    @event = Event.find(params[:event_id])
    if params[:checkin_id]
      time = @event.checkins.where(:id => params[:checkin_id]).first.created_at
      @checkins = @event.checkins.order(:created_at).where(:created_at => (time + 1.second)..Time.zone.now).limit(4)
    else
      @checkins = @event.checkins.order(:created_at).limit(4)
    end
    respond_with(@event) do |format|
      format.html

      format.json do
        render :json => @checkins.to_json(:only => [:id, :employer, :employ, :employment, :shoutout], :include => [:user => {:only => [:name]}])
      end
    end
  end

  def rafflr
    @event = Event.find(params[:event_id])
    @checkins = @event.checkins
    respond_with(@event) do |format|
      format.html
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_carousel.js.erb
var data = {};

$.ajaxPollSettings.interval = 5000;

$.ajaxPollSettings.successCondition = function(result) {
  return result != null; // custom condition goes here.
};

function addCarouselItem(item) {
  var li = $("<li class=\"checkin transition\"></li>");
  var summary = $("<div class=\"summary\"></div>");
  var title_span = $("<span class=\"title\">" + item.user.name + ($.trim(item.employer) == "" ? "" : " with ") + item.employer + "</span>");
  if(item.employment) {
    title_span.append($("<span class=\"ui-li-count\">Looking For Work</span>"));
  }
  if(item.employ) {
    title_span.append($("<span class=\"ui-li-count\">Looking To Hire</span>"));
  }
  var title = $("<p class=\"title ui-li-desc\"></p>");
  title.append(title_span);
  var content = $("<p class=\"meta\"><span class=\"shoutout\">" + item.shoutout + "</span></p>");
  summary.append(title);
  summary.append(content);
  li.append(summary);
  li.fadeIn(2000, function() {
    $(this).removeClass("transition");
  });
  $("ul.carousel").append(li);
}

$(document).live("pageshow", function() {
  $("ul.carousel").live("updatelayout", function() {
    var carousel = $("ul.carousel");
    if(carousel.offset().top + carousel.height() > $(window).height()) {
      setTimeout("$.mobile.silentScroll(" + carousel.height() + ")", 100);
    }
  });

  $.ajaxPoll({
    url: '<%= event_carousel_path(@event) %>',
    type: "GET",
    data: data,
    dataType: "json",
    success: function(result) {
      this.completed = $(".page[data-url='<%= event_carousel_path(@event) %>']:visible").length == 0;
      $.each(result, function(indexInArray, valueOfElement) {
        data.checkin_id = valueOfElement.id;
        addCarouselItem(valueOfElement);
      });
      if(result.length > 0) {
        $("ul.carousel").listview("refresh");
      }
    }
  });
});

app/views/events/_checkin.html.slim
- if event.active? && !event.is_checked_in(current_user)
  p
    = link_to "Check In", new_event_checkin_path(event), :"data-role" => "button"

app/views/events/_content.html.slim
h3.ui-li-heading
  = event.name
p.ui-li-desc
  | Starts at: #{event.start_datetime.strftime("%A %B %e, %Y %l:%M %p").squeeze(" ")}
p.ui-li-desc
  | Ends at: #{event.end_datetime.strftime("%A %B %e, %Y %l:%M %p").squeeze(" ")}

app/views/events/_event.html.slim
li.event
  - if can? :read, event
    a href="#{event_path(event)}"
      = render :partial => 'content', :locals => {:event => event}
      - if event.is_checked_in(current_user)
        p.ui-li-desc Checked In
    = render :partial => "checkin", :locals => {:event => event}
  - else
    = render :partial => 'content', :locals => {:event => event}
    = render :partial => "checkin", :locals => {:event => event}
  = link_to("Edit", edit_event_path(event), :method => :get) if can? :update, event

app/views/events/_form.html.slim
div data-role="fieldcontain"
  = f.label :name
  = f.text_field :name

div data-role="fieldcontain"
  = f.label :description
  = f.text_area :description

div data-role="fieldcontain"
  = f.label :start_date
  = f.text_field :start_date, :"data-role" => "datebox", :"data-options" => '{"mode": "flipbox", "dateFormat":"%Y-%m-%d", "closeCallback": "$(\"#event_start_time\").datebox(\"open\");"}'
  = f.label :start_time
  = f.text_field :start_time, :"data-role" => "datebox", :"data-options" => '{"mode": "timebox", "timeFormatOverride": 12}'

div data-role="fieldcontain"
  = f.label :end_date
  = f.text_field :end_date, :"data-role" => "datebox", :"data-options" => '{"mode": "flipbox", "dateFormat":"%Y-%m-%d", "closeCallback": "$(\"#event_end_time\").datebox(\"open\");"}'
  = f.label :end_time
  = f.text_field :end_time, :"data-role" => "datebox", :"data-options" => '{"mode": "timebox", "timeFormatOverride": 12}'

app/views/events/_rafflr.js.erb
$(document).ready(function() {
  var started = false;

  $("button.start").click(function() {
    if(started) {
      location.reload(true);
    } else {
      var winners = parseInt($(".winners").val());

      if(winners && winners > 0) {
        started = true;
        var rafflr = $("body").rafflr({
          url: "<%= event_checkins_path(@event, :format => :json, :rafflr => true) %>",
          winners: winners
        });

        $(this).html("Stop");

        rafflr.data("rafflr").start();
      } else {
        alert("Please enter a valid number of winners.");
      }
    }
  })
});

app/views/events/carousel.html.slim
- content_for :javascript do
  script type="text/javascript"
    - with_format('js') do
      = render :partial => "carousel"

h2
  = @event.name
ul.checkins.carousel data-role="listview"

app/views/events/edit.html.slim
h2
  | Edit Event "#{@event.name}"
= form_for @event do |form|
  = render :partial => "form", :locals => {:f => form}
  p
    button type="submit" class="ui-btn-hidden"
      | Submit

app/views/events/index.html.slim
ul data-role="listview" data-split-icon="#{'gear' if can? :manage, @event}"
  = render :partial => "event", :collection => @events

  - if @events.current_page > 1
    li.ui-pagination-prev
      a href="#{events_path(:page => @events.current_page - 1)}"
        | Prev
  - if @events.current_page < @events.total_pages
    li.ui-pagination-next
      a href="#{events_path(:page => @events.current_page + 1)}"
        | Next

app/views/events/new.html.slim
.events data-role="page" data-title="New Events"
  h2
    | Create New Event
  = form_for @event do |form|
    = render :partial => "form", :locals => {:form => form}
    p
      button type="submit" class="ui-btn-hidden"
        | Add Event

app/views/events/rafflr.html.slim
- content_for :javascript do
  = javascript_include_tag "d3.v2", "rafflr"
  script type="text/javascript"
    - with_format('js') do
      = render :partial => "rafflr"
.title
  span
    | Rafflr 2.0
  .controls
    label for="winners"
      | Winners:
    input.winners type="number" name="winners" size="3" value="3" data-role="none"
    button.start data-inline="true" data-role="none"
      | Start

app/views/events/show.html.slim
h2
  = @event.name
p
  pre
    = @event.description
p
  | Starts at: #{@event.start_datetime.strftime("%A %B %e, %Y %l:%M %p").squeeze(" ")}
p
  | Ends at: #{@event.end_datetime.strftime("%A %B %e, %Y %l:%M %p").squeeze(" ")}
- if @event.is_checked_in(current_user)
  | Checked In<br/>
- elsif @event.active?
  = link_to "Check In", new_event_checkin_path(@event), :"data-role" => "button", :"data-inline" => "true"
- if @event.is_in_rafflr(current_user)
  | Entered in to Rafflr
- elsif @event.active? && @event.is_checked_in(current_user)
  = link_to "Enter in to Rafflr", event_checkin_rafflr_path(@event, @event.checkins.find_by_user_id(current_user.id)), :target => "_self", :"data-role" => "button", :"data-inline" => "true"

p
  = link_to "Checkin Carousel", event_carousel_path(@event), :method => :get, :"data-role" => "button", :"data-inline" => "true", :target => "_self"
  = link_to "Rafflr", event_rafflr_path(@event), :method => :get, :"data-role" => "button", :"data-inline" => "true", :target => "_self"
p
  - if can? :update, @event
    = link_to "Edit", edit_event_path(@event), :method => :get, :"data-role" => "button", :"data-inline" => "true"
    = link_to "Delete", event_path(@event), :method => :delete, :"data-role" => "button", :"data-inline" => "true"

h3
  | Current checkins
div data-role="controlgroup" data-type="horizontal"
  = link_to "Looking for Work", event_path(@event, :work => true), :"data-role" => "button", :class => "#{'ui-btn-active' if params[:work]}"
  = link_to "All", event_path(@event), :"data-role" => "button", :class => "#{'ui-btn-active' unless params[:hire] || params[:work]}"
  = link_to "Looking to Hire", event_path(@event, :hire => true), :"data-role" => "button", :class => "#{'ui-btn-active' if params[:hire]}"
ul.checkins data-role="listview" data-filter="true" data-split-icon="#{'delete' if can? :manage, @event}"
  = render :partial => "checkins/checkin", :collection => @checkins