config/routes.rb
Raor::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :events do
    resources :checkins do
      get 'rafflr'
    end
    get 'carousel'
    get 'rafflr'
  end
  resources :admin_users, :controller => "users"
  root :to => "events#index"

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  before_save :set_employer

  attr_accessor :current_user, :remember_employer
  attr_accessible :employ, :employer, :employment, :event_id, :rafflr, :remember_employer, :shoutout, :user_id, :as => :default
  attr_accessible :created_at, :employ, :employer, :employment, :event_id, :hidden, :rafflr, :remember_employer, :shoutout, :updated_at, :user_id, :as => :admin

  scope :hidden, -> { where(hidden: true) }
  scope :unhidden, -> { where(hidden: false) }
  scope :employ, -> { where(employ: true) }
  scope :employment, -> { where(employment: true) }
  scope :rafflr, -> { where(rafflr: true) }

  validates :employ, :inclusion => {:in => [true, false]}
  validates :employment, :inclusion => {:in => [true, false]}
  validates :rafflr, :inclusion => {:in => [true, false]}
  validates :remember_employer, :inclusion => {:in => [true, false, "1", "0", 1, 0]}
  validates :employer, :format => {:with => /\A[\x20-\x7E]*\z/}, :length => {:within => 0..254}
  validate :is_user
  validates :shoutout, :format => {:with => /\A[\x20-\x7E]*\z/}, :length => {:within => 0..254}

  def remember_employer
    @remember_employer ||= (current_user ? current_user.remember_employer : false)
  end

  private
  def is_user
    errors[:base] << "Attempting to checkin as another user is a no-no!" unless self.current_user.present? && self.user_id == self.current_user.id
  end

  def set_employer
    self.current_user.update_attributes(:employer => self.employer, :remember_employer => @remember_employer)
  end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_filter lambda{params[:id] = params[:checkin_id]}, :only => :rafflr
  load_and_authorize_resource :event
  load_and_authorize_resource :checkin, :through => :event

  respond_to :html, :json

  def index
    case as_what?
      when :admin
      else
        @checkins = Checkin.unhidden
    end

    if params[:rafflr] == "true"
      @checkins = @checkins.rafflr
    end

    respond_with(@event, @checkins) do |format|
      format.html

      format.json do
        render :json => @checkins, :include => :user
      end
    end
  end

  def show
    respond_with(@checkin)
  end

  def new
    @checkin.current_user = current_user
    @checkin.employer = @checkin.current_user.employer if @checkin.remember_employer
    respond_with(@checkin)
  end

  def create
    respond_with(@event, @checkin) do |format|
      @checkin.assign_attributes(params[:checkin], :as => as_what?)
      @checkin.user_id = current_user.id
      @checkin.current_user = current_user
      @checkin.event_id = @event.id

      format.html do
        if @checkin.save
          flash[:notice] = "Successfully checked in to #{@event.name}"
          redirect_to event_path(@event)
        else
          flash[:alert] = "Failed to check in to #{@event.name}"
          redirect_to event_path(@event)
        end
      end
    end
  end

  def edit
    @checkin.current_user = current_user
    respond_with(@checkin)
  end

  def update
    @checkin.current_user = current_user
    respond_with(@event, @checkin) do |format|
      format.html do
        if params[:checkin]
          if @checkin.update_attributes(params[:checkin])
            flash[:notice] = "Successfully updated checkin status for #{@checkin.event.name}"
            redirect_to event_path(@event)
          else
            flash[:alert] = "Failed to update checkin status"
            redirect_to new_event_path
          end
        else
          if @event && @checkin.save
            flash[:notice] = "Successfully checked in to event #{@event.name}"
            redirect_to event_path(@event)
          else
            flash[:alert] = "Failed to check in to event #{@event.name}"
            redirect_to new_event_path
          end
        end
      end
    end
  end

  def destroy
    respond_with(@event, @checkin) do |format|
      name = @checkin.current_user.name if @checkin.current_user

      format.html do
        if @checkin.destroy
          flash[:notice] = "Successfully destroyed checkin for #{name}"
          redirect_to event_path(@event)
        else
          flash[:alert] = "Failed to destroy checkin for #{name}"
        end
      end
    end
  end

  def rafflr
    @checkin.current_user = current_user
    respond_with(@event, @checkin) do |format|
      format.html do
        if @checkin.update_attributes(:rafflr => true)
          flash[:notice] = "Successfully updated checkin status for #{@checkin.event.name}"
          redirect_to event_path(@event)
        else
          flash[:alert] = "Failed to update checkin status"
          redirect_to new_event_path
        end
      end
    end
  end
end

app/helpers/checkin_helper.rb
module CheckinHelper
  def checkin_link event
    link_to checkin_path(event)
  end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
  def checkin_link event
    button_to checkin_path(event)
  end
end

app/views/checkins/_checkin.html.slim
li.checkin
  - if can? :manage, @event
    a.summary
      = render :partial => 'checkins/content', :locals => {:checkin => checkin}
  - else
    .summary
      = render :partial => 'checkins/content', :locals => {:checkin => checkin}
  = link_to("Delete", event_checkin_path(@event, checkin), :method => :delete, :confirm => "Are you sure you want to delete this checkin?", :"data-icon" => "delete") if can? :manage, @event

app/views/checkins/_content.html.slim
p.title
  span.title
    = checkin.employer.blank? ? checkin.user.name : "#{checkin.user.name} with #{checkin.employer}"
    - unless checkin.employ.blank?
      span.ui-li-count
        | Looking To Hire
    - unless checkin.employment.blank?
      span.ui-li-count
        | Looking For Work
p.shoutout
  = checkin.shoutout

app/views/checkins/_form.html.slim
div data-role="fieldcontain"
  fieldset data-role="controlgroup" data-type="horizontal"
    = f.check_box :employment
    = f.label :employment, "Looking For Work"

    = f.check_box :employ
    = f.label :employ, "Looking To Hire"
div data-role="fieldcontain"
  = f.label :employer, "Employer (optional)"
  = f.text_field :employer
  = f.check_box :remember_employer
  = f.label :remember_employer, :"data-inline" => true
div data-role="fieldcontain"
  = f.label :shoutout, "Shout-out!"
  = f.text_field :shoutout
div data-role="fieldcontain"
  = f.check_box :rafflr
  = f.label :rafflr, "Enter in to Rafflr", :"data-inline" => true

app/views/checkins/edit.html.slim
h2
  | Edit Checkin for #{@checkin.event.name}
= form_for @checkin do |form|
  = render :partial => "form", :locals => {:f => form}
  p
    = form.submit "Update Checkin"

app/views/checkins/index.html.slim
h2
  | Checkins for event "#{@event.name}"
.event_checkins
  ul#checkins data-role="listview"
    = render :partial => "checkin", :collection => @checkins

app/views/checkins/new.html.slim
h2
  | Checkin to #{@event.name}
= form_for [@event, @checkin] do |form|
  = render :partial => "form", :locals => {:f => form}
  p
    button type="submit" class="ui-btn-hidden"
      | Checkin